### ISSUE TITLE
add albatross conversion factor to expcatchnum for neus public data

### ISSUE THREAD

**Issue by mstuart1** [pinskylab/OceanAdapt#110]

**Comment by mstuart1** [comment]
I emailed Sean Lucey to see if he can share code and or a file of conversion factors for species.  [This paper](https://www.nefsc.noaa.gov/publications/crd/crd1005/crd1005.pdf) describes the development of the conversion factors and might list all of them but they would have to be typed in by hand unless we can get a file from NOAA.

**Comment by mstuart1** [comment]
Created branch called neus-public-source to work on this issue.  Applying the conversion from Sean Lucey cuts out all years before 2009.  Not the desired effect.  Unsure how to apply the conversion factors.  At this point, emailing Sean Lucey for the updated data is the most efficient route.

**Comment by mpinsky** [comment]
Update from Sean Lucey: as long as we get the data from him, the conversion factors have already been applied.
