### ISSUE TITLE
Create a docker file to preserve the OceanAdapt version environment

### ISSUE THREAD

**Issue by mstuart1** [pinskylab/OceanAdapt#116]

**Comment by rBatt** [comment]
Good idea. Can you use conda environments with R? I know that in anaconda3.4 you can install rstudio ... I’m. It sure, but that might also mean it preserves virtual environments for r. Might be easier if you don’t need to manage a whole system, and just need to swap between versions of R and R packages.

**Comment by mstuart1** [comment]
You can use conda with R.  I was thinking Docker because not all users use linux, or command line.   Or is there a desktop gui for conda?

**Comment by rBatt** [comment]
You get "anaconda navigator" which looks like this:

<img width="1107" alt="Screen Shot 2020-01-26 at 8 14 23 AM" src="https://user-images.githubusercontent.com/5630847/73135747-e5ab8180-4013-11ea-8125-d5d0d8ee8297.png">

In the "home" tab you can see your applications, which some folks like.

I never use the GUI. I just use the command line.

**Comment by mstuart1** [comment]
It is possible that the ORA will create the environment based on the mosaic server that runs the OceanAdapt scripts and will supply that environment to the Pinsky Lab for them to run the compile.R script.
