### ISSUE TITLE
Broken link for Detailed Metadata

### ISSUE THREAD

**Issue by mpinsky** [pinskylab/OceanAdapt#119]
The link from the bottom of the About Us page for "Detailed Metadata" links to https://github.com/pinskylab/OceanAdapt/tree/master/meta-data, but this page does not appear to exist. We get a 404 Page Not Found error

**Comment by danfarns** [comment]
Altered link from:
https://github.com/pinskylab/OceanAdapt/tree/master/meta-data
to
https://github.com/pinskylab/OceanAdapt/tree/master/metaData

@mstuart1 
Please confirm this is the correct link. 😸

**Comment by mstuart1** [comment]
Best link would be https://pinskylab.github.io/OceanAdapt/metaData/index.html @danfarns

**Comment by danfarns** [comment]
Link has been updated. 

Closing issue.
