### ISSUE TITLE
Conversion factor problems with NEUS data

### ISSUE THREAD

**Issue by df511** [pinskylab/OceanAdapt#146]
"Adam discovered some things that looked really strange when we were digging into an analysis that involved haddock a few months ago.  Since that time, we have been working with Sean Lucey (our source for the data) to identify and resolve a series of problems in the retrievals that arose before past data sets were delivered to us.  These problems involved vessel conversion factors not being applied to abundance for all species and incorrect conversion values being used for a few species (standard error of conversion factor used instead of the mean estimate for haddock, butterfish, and windowpane) in the 2020 retrieval." - Kathy Mills

This link can be used to compare the 2020 retrieval (Survdat_Nye_Aug_2020) to the new retrieval:

https://adamkemberling.github.io/nefsc_trawl/R/qaqc_reports/abundance_biomass_check_2020.html

You’ll see here that the abundance values match much better, except for haddock and butterfish (windowpane is a mismatch too but isn’t shown because it wasn’t in Andrew’s paper). And the biomass discrepancies are reduced as well.

**Comment by df511** [comment]
Hi Kathy and Malin,

![image](https://user-images.githubusercontent.com/30601505/116588969-29adc600-a8ea-11eb-9b29-a766ba2aa35a.png)![image](https://user-images.githubusercontent.com/30601505/116589040-3d592c80-a8ea-11eb-8064-cb0d870da4a8.png)Thanks so much for bringing this to our attention, Kathy! This year I decided to retrieve the data directly from the open data portal. I'm still communicating with the NMFS team about conversion factors (Sean Lucey wasn't aware of the open data team's practices), but in the meantime, I plotted our data to compare to the plots on Adam's GitHub page. Here's the one for Acadian Redfish (Sebastes fasciatus):![image](https://user-images.githubusercontent.com/30601505/116589094-477b2b00-a8ea-11eb-94a7-12a1803216f3.png)
![image](https://user-images.githubusercontent.com/30601505/116588982-2e727a00-a8ea-11eb-83bb-9d54755833a2.png)

And the one from Adam's page: 

![image](https://user-images.githubusercontent.com/30601505/116589040-3d592c80-a8ea-11eb-8064-cb0d870da4a8.png)
![image](https://user-images.githubusercontent.com/30601505/116589094-477b2b00-a8ea-11eb-94a7-12a1803216f3.png)


Our data look strikingly similar to the "newest Survdat," which makes me think that all is well (e.g., the spike in 2009 isn't there); however, the actual numbers are off by a bit. Adam's biomass (y-axis) tends to be lower than ours. Perhaps there was another filtration of the data before plotting that I'm not aware of...

Either way, signs look good that we aren't running into this issue via the open data portal (fall and spring surveys).

- Dan

**Comment by df511** [comment]
Script used to generate above plot:

```
test <- neus_fall[neus_fall$spp == "SEBASTES FASCIATUS",]
test2 <- test  %>%
    filter(year >= 2008,
           year <= 2019)
test2 <- aggregate(test2['wtcpue'], by=test2['year'], sum)
plot(test2, type = 'l')

test <- neus_spring[neus_spring$spp == "SEBASTES FASCIATUS",]
test3 <- test  %>%
  filter(year >= 2008,
         year <= 2019)
test3 <- aggregate(test3['wtcpue'], by=test3['year'], sum)
plot(test3, type = 'l')


test4 <- rbind(test2,test3)

test5 <- aggregate(test4['wtcpue'], by=test4['year'], sum)

plot(test5, type = "l", main = "Acadian Redfish")
```

**Comment by df511** [comment]
Hi @mpinsky, I've applied the conversion factors to the NEUS data and confirmed that the code works as expected. I then compared our data to the survdat files we had last year, and things aren't quite lining up. For starters, there aren't even the same number of records (over the same time period). I'm still investigating, but I think there may be some discrepancies between what is posted publicly and what Sean provides us. 

This also leads to some differences in wtcpue through time for some species I tested. The differences aren't consistent as far as I can tell. There are a lot of moving parts here, so I'm just piecing through it bit by bit to identify the root cause. I will hopefully get to the bottom of this by tonight.

I'll continue to post updates here throughout the afternoon/evening.

**Comment by df511** [comment]
Plots for data comparison (new = public, old = Survdat) for Acadian Redfish, 2008-2019, each season
![image](https://user-images.githubusercontent.com/30601505/118690296-ed2d0600-b7d5-11eb-940f-b115e4707e0f.png)![image](https://user-images.githubusercontent.com/30601505/118690342-f9b15e80-b7d5-11eb-866d-9edcd6926e21.png)![image](https://user-images.githubusercontent.com/30601505/118690374-00d86c80-b7d6-11eb-809b-e47025ced33b.png)![image](https://user-images.githubusercontent.com/30601505/118690409-0766e400-b7d6-11eb-8acf-5e53d763759a.png)

**Comment by df511** [comment]
Now for total (Fall + Spring)![image](https://user-images.githubusercontent.com/30601505/118690805-6b89a800-b7d6-11eb-86b8-d905dacfa345.png)![image](https://user-images.githubusercontent.com/30601505/118690767-60367c80-b7d6-11eb-953d-683a1efb36ad.png)

**Comment by mpinsky** [comment]
Congrats on getting it working! But great to be digging in more to
understand the differences. If there are still differences after you feel
like you've eliminated coding mistakes, it would be worth circling back
with Sean or Phil.

**Comment by df511** [comment]
Hey @mpinsky  , still some differences in terms of the # of records, but the biomass data look good! I caught one small typo in one of the conversions. ![image](https://user-images.githubusercontent.com/30601505/118698926-f7073700-b7de-11eb-9434-b265823ddd4f.png)![image](https://user-images.githubusercontent.com/30601505/118698876-ebb40b80-b7de-11eb-914d-bf79748ebfb5.png)

**Comment by df511** [comment]
Just tested another few species. Everything looks goods now!

**Comment by df511** [comment]
Scripts to generate plots for reciprocity
`load("data_raw/neus_Survdat.RData")
load("data_raw/neus_SVSPP.RData")

neus_survdat <- survdat %>% 
  # select specific columns
  select(CRUISE6, STATION, STRATUM, SVSPP, CATCHSEX, SVVESSEL, YEAR, SEASON, LAT, LON, DEPTH, SURFTEMP, SURFSALIN, BOTTEMP, BOTSALIN, ABUNDANCE, BIOMASS) %>% 
  # remove duplicates
  distinct() %>% 
  mutate(SVVESSEL = as.character(SVVESSEL), 
         SEASON = as.character(SEASON))

# sum different sexes of same spp together
neus_survdat <- neus_survdat %>% 
  group_by(YEAR, SEASON, LAT, LON, DEPTH, CRUISE6, STATION, STRATUM, SVSPP) %>% 
  summarise(wtcpue = sum(BIOMASS)) 


# repeat for spp file 
neus_spp <- spp %>%
  # remove some columns from spp data
  select(-ITISSPP, -COMNAME, -AUTHOR) %>% 
  mutate(SCINAME = as.character(SCINAME))

files <- as.list(dir(pattern = "neus_strata", path = "data_raw", full.names = T))

neus_strata <- read_csv("data_raw/neus_strata.csv") %>% 
  select(stratum, stratum_area) %>% 
  mutate(stratum = as.integer(stratum)) %>%
  distinct()

neus <- left_join(neus_survdat, neus_spp, by = "SVSPP") %>%
  left_join(neus_strata, by = c("STRATUM" = "stratum"))

neus <- filter(neus, !is.na(stratum_area))

# are there any strata in the data that are not in the strata file?
stopifnot(nrow(filter(neus, is.na(stratum_area))) == 0)

neus <- neus %>%
  mutate(
    # Create a unique haulid
    haulid = paste(formatC(CRUISE6, width=6, flag=0), formatC(STATION, width=3, flag=0), formatC(STRATUM, width=4, flag=0), sep='-'),  
    # Calculate stratum area where needed (use convex hull approach)
    # convert square nautical miles to square kilometers
    stratumarea = stratum_area * 3.429904) %>% 
  rename(year = YEAR,
         spp = SCINAME,
         lat = LAT, 
         lon = LON, 
         depth = DEPTH,
         stratum = STRATUM) %>%
  filter(
    # remove unidentified spp and non-species
    spp != "" | !is.na(spp), 
    !grepl("EGG", spp), 
    !grepl("UNIDENTIFIED", spp)) %>%
  group_by(haulid, stratum, stratumarea, year, lat, lon, depth, spp, SEASON) %>% 
  summarise(wtcpue = sumna(wtcpue)) %>% 
  # add temporary region column (this will be replaced with seasonal name)
  mutate(region = "Northeast US") %>% 
  select(region, haulid, year, lat, lon, stratum, stratumarea, depth, spp, wtcpue, SEASON) %>% 
  ungroup()

# now that lines have been removed from the main data set, can split out seasons
# NEUS spring ====
neusS <- neus %>% 
  ungroup() %>% 
  filter(SEASON == "SPRING") %>% 
  select(-SEASON) %>% 
  mutate(region = "Northeast US Spring")

# NEUS Fall ====
neusF <- neus %>% 
  ungroup() %>% 
  filter(SEASON == "FALL") %>% 
  select(-SEASON) %>% 
  mutate(region = "Northeast US Fall")

test <- neus_fall%>%
  filter(year >= 2008,
         year <= 2019)

test2 <- neusF%>%
  filter(year >= 2008,
         year <= 2019)



test <- neus_fall[neus_fall$spp == "SEBASTES FASCIATUS",]
test2 <- test  %>%
  filter(year >= 2008,
         year <= 2019)
test2 <- aggregate(test2['wtcpue'], by=test2['year'], sum)
plot(test2, type = 'l', main = "Acadian Redfish - Fall (new)")

test <- neus_spring[neus_spring$spp == "SEBASTES FASCIATUS",]
test3 <- test  %>%
  filter(year >= 2008,
         year <= 2019)
test3 <- aggregate(test3['wtcpue'], by=test3['year'], sum)
plot(test3, type = 'l',  main = "Acadian Redfish - Spring (new)")


test4 <- rbind(test2,test3)

test5 <- aggregate(test4['wtcpue'], by=test4['year'], sum)

plot(test5, type = "l", main = "Acadian Redfish (new)")


test <- neusF[neusF$spp == "SEBASTES FASCIATUS",]
test2 <- test  %>%
  filter(year >= 2008,
         year <= 2019)
test2 <- aggregate(test2['wtcpue'], by=test2['year'], sum)
plot(test2, type = 'l', main = "Acadian Redfish - Fall (old)")

test <- neusS[neusS$spp == "SEBASTES FASCIATUS",]
test3 <- test  %>%
  filter(year >= 2008,
         year <= 2019)
test3 <- aggregate(test3['wtcpue'], by=test3['year'], sum)
plot(test3, type = 'l',  main = "Acadian Redfish - Spring (old)")


test4 <- rbind(test2,test3)

test5 <- aggregate(test4['wtcpue'], by=test4['year'], sum)

plot(test5, type = "l", main = "Acadian Redfish (old)")



test <- neus_fall[neus_fall$spp == "CARCHARIAS TAURUS",]
test2 <- test  %>%
  filter(year >= 2008,
         year <= 2019)
test2 <- aggregate(test2['wtcpue'], by=test2['year'], sum)
#plot(test2, type = 'l', main = "Acadian Redfish - Fall (new)")

test <- neus_spring[neus_spring$spp == "CARCHARIAS TAURUS",]
test3 <- test  %>%
  filter(year >= 2008,
         year <= 2019)
test3 <- aggregate(test3['wtcpue'], by=test3['year'], sum)
#plot(test3, type = 'l',  main = "Sand Tiger - Spring (new)")


test4 <- rbind(test2,test3)

test5 <- aggregate(test4['wtcpue'], by=test4['year'], sum)

plot(test5, type = "l", main = "Sand Tiger (new)")


test <- neusF[neusF$spp == "CARCHARIAS TAURUS",]
test2 <- test  %>%
  filter(year >= 2008,
         year <= 2019)
test2 <- aggregate(test2['wtcpue'], by=test2['year'], sum)
#plot(test2, type = 'l', main = "Sand Tiger - Fall (old)")

test <- neusS[neusS$spp == "CARCHARIAS TAURUS",]
test3 <- test  %>%
  filter(year >= 2008,
         year <= 2019)
test3 <- aggregate(test3['wtcpue'], by=test3['year'], sum)
#plot(test3, type = 'l',  main = "Sand Tiger - Spring (old)")


test4 <- rbind(test2,test3)

test5 <- aggregate(test4['wtcpue'], by=test4['year'], sum)

plot(test5, type = "l", main = "Sand Tiger (old)")


test <- neus_fall[neus_fall$spp == "CANCER IRRORATUS",]
test2 <- test  %>%
  filter(year >= 2008,
         year <= 2019)
test2 <- aggregate(test2['wtcpue'], by=test2['year'], sum)
#plot(test2, type = 'l', main = "Atlantic Rock Crab - Fall (new)")

test <- neus_spring[neus_spring$spp == "CANCER IRRORATUS",]
test3 <- test  %>%
  filter(year >= 2008,
         year <= 2019)
test3 <- aggregate(test3['wtcpue'], by=test3['year'], sum)
#plot(test3, type = 'l',  main = "Atlantic Rock Crab - Spring (new)")


test4 <- rbind(test2,test3)

test5 <- aggregate(test4['wtcpue'], by=test4['year'], sum)

plot(test5, type = "l", main = "Atlantic Rock Crab (new)")


test <- neusF[neusF$spp == "CANCER IRRORATUS",]
test2 <- test  %>%
  filter(year >= 2008,
         year <= 2019)
test2 <- aggregate(test2['wtcpue'], by=test2['year'], sum)
#plot(test2, type = 'l', main = "Atlantic Rock Crab - Fall (old)")

test <- neusS[neusS$spp == "CANCER IRRORATUS",]
test3 <- test  %>%
  filter(year >= 2008,
         year <= 2019)
test3 <- aggregate(test3['wtcpue'], by=test3['year'], sum)
#plot(test3, type = 'l',  main = "Atlantic Rock Crab - Spring (old)")


test4 <- rbind(test2,test3)

test5 <- aggregate(test4['wtcpue'], by=test4['year'], sum)

plot(test5, type = "l", main = "Atlantic Rock Crab (old)")`
