### ISSUE TITLE
trouble updating the data on the website

### ISSUE THREAD

**Issue by mikeallen-eco** [pinskylab/OceanAdapt#153]
Based on a note from NJAES on Thursday, October 28, 2021: 
The master branch in the GitHub does not seem to incorporate fixes that were supposed to be made for the script to be able to run without intervention.

1. (Halting Error) wcann_catch (line 809/810). `wcann_catch.csv` was zipped into `wcann_catch.csv.zip` so the file does not exist. I remember catching this previously.
2. (Halting Error) temp on line 3358 references a local directory. I caught this previously, so maybe a change didn't go through.
3. (Data Problem) Someone removed the common name column from the BY_SPECIES_DATA table, so I don't have the common names for fish right now. This was added previously since there were multiple `spp` rows with different `common` names.

**Comment by mpinsky** [comment]
Hey @mikeallen-eco , can we close this now?

**Comment by mikeallen-eco** [comment]
Yes, we've addressed them.
