### ISSUE TITLE
description of columns as being crossed/nested

### ISSUE THREAD

**Issue by rBatt** [pinskylab/OceanAdapt#18]
For example, HAUL might be an integer number that counts up within a cruise in a year. So HAUL is crossed with CRUISE (I'm pretty sure). On the other hand, latitude and longitude are nested within STRATUM.

The issue is where to place this type of information, and how to do it for all columns and data sets in a reasonable and standardized way.

**Comment by rBatt** [comment]
@mpinsky I'm considering this to now longer be of basic Meta Data functionality, and is instead something that the user needs to infer from the data structure. Maybe that's a little cruel to the user, but it will take too long to get it to be a part of the formal MD structure.

**Comment by rBatt** [comment]
This is done in `trawlData::trawlAgg`; could borrow from that

**Comment by ljmarxen** [comment]
I am out of the office until 6/29/16.

Your message was received and I will read it when I return. Any future
messages from you between now and when I return will be read at that
time also, but you will not receive any more automatic replies to that
effect.

If you feel that this issue requires immediate assistance, please contact
Dan Farnsworth at danfarns@rci.rutgers.edu.

**Comment by mstuart1** [comment]
I'm closing this issue because I don't think we need to address this anymore.
