### ISSUE TITLE
Source stratum area instead of calculating

### ISSUE THREAD

**Issue by mstuart1** [pinskylab/OceanAdapt#70]
Currently, GOA and NEUS contain strata that are not in their original strata documents.  The original source of the strata documents was that Malin hand typed them based on the meta data from the sources.  

We are currently calculating the new stratum areas based on this [script](https://github.com/mpinsky/OceanAdapt/blob/update_2019/R/calc_strata.R).  

It would be better to source those stratum area from the original data sources if possible.  Search for literature that contains stratum area for these undefined strata.

**Comment by mstuart1** [comment]
Try using R package pasta to import the new data.

**Comment by mstuart1** [comment]
@mpinsky GOA currently has strata in the trawl data that are not defined in the original goa_strata.csv which you hand typed based on the [vonSzalay paper](https://github.com/mpinsky/OceanAdapt/blob/master/metaData/docs/goa/von%20Szalay%20et%20al.%202010%20NOAA-TM-AFSC-208.pdf).  

I am about to hand type the new strata, however it looks like these strata are combinations of original strata, for example, stratum code 911 is a combination of strata 10-13.  Stratum code 913 is stratum 210.  Do I need to account for this somehow or is it enough that it is in the paper in the metadata?

**Comment by mpinsky** [comment]
It has been long enough that I don't remember all the details. I leave it
to your judgement how to proceed, though I would err on including more
information and leaving breadcrumbs so that we and others in the future can
understand how all the pieces fit together. Maybe another column in the
stratum file explaining the strata combinations? Or something clear in the
metadata.

**Comment by mstuart1** [comment]
GOA strata were all accounted for.  NEUS strata remain undefined.  The most recent publication we have defining the strata is from 1988.  It does not cover strata that begin in the 3000-8000's.  I emailed Sean Lucy and am waiting for a response.

**Comment by mstuart1** [comment]
Sean Lucey sent an updated strata file with all strata for NEUS.

**Comment by mstuart1** [comment]
NEUS trawl data still contains some strata that were not in Sean Lucey's file.  He forwarded the email through a chain that ended up here:

Hi Michelle,
The Ecosystems Surveys Branch (ESB) is happy to help and we should be considered the primary contact for NEFSC survey data requests. Unfortunately we cannot answer your specific questions since we did not supply you with the data that you are currently working with. To ensure that you receive the information that you need, please submit your original data request to the appropriate program within ESB. For all data requests related to our Bottom Trawl Survey, please contact Phil Politis (CC'd). Please contact me for data requests related to any of our shellfish surveys. Please let me know if you have any questions, I'd be happy to discuss. Thanks!
Pete

Peter Chase
peter.chase@noaa.gov
Acting Chief, Ecosystems Surveys Branch
NOAA Fisheries/Northeast Fisheries Science Center
166 Water Street
Woods Hole, MA 02543
(508) 495-2348

**Comment by mpinsky** [comment]
OK. Looks like the next step is to request stratum areas for the Bottom
Trawl Survey from Phil.

**Comment by mstuart1** [comment]
After phone call with Phil, he will send zip files of NEUS data

**Comment by mstuart1** [comment]
The zip file from Phil lacks more than a million rows of data.
