### ISSUE TITLE
Taxonomic cleaning

### ISSUE THREAD

**Issue by AquaAuma** [pinskylab/OceanAdapt#97]
Hi Michelle, Ryan, and Malin,

1. I cleaned all US surveys (excluding Scotian Shelf) using the OceanAdapt code and noticed that if someone wishes to include some taxonomic rank info. from the 'spptaxonomy.csv' file such as order/family or so, there are some duplicates in the csv file which have similar taxon names, but different classification.
Therefore it creates rows in the final data, even after using the 'distinct()' command.
Maybe the duplicated taxon in the 'spptaxonomy.csv' should be removed. Here is the list:

 [1] "AETOBATUS NARINARI"            "ANASIMUS LATUS"               
 [3] "CITHARICHTHYS"                 "DIAPHUS"                      
 [5] "DIPLODUS HOLBROOKII"           "ETROPUS"                      
 [7] "LIMANDA FERRUGINEA"            "NEZUMIA BAIRDII"              
 [9] "NOETIA PONDEROSA"              "OVALIPES"                     
[11] "PARALEPIDIDAE"                 "PARALICHTHYS"                 
[13] "PEPRILUS TRIACANTHUS"          "PSEUDOPLEURONECTES AMERICANUS"
[15] "SYMPHURUS"                     "UROPHYCIS"                    
[17] "UROPHYCIS EARLLII"

2. Also, the taxonomic file does not cover all 'spp' names from the surveys and I ended up with species names without their corresponding 'taxon' in the file 'spptaxonomy.csv' (>800), and include several fish species (such as winter flounder and several sebastes species) from several surveys (EBS, GOA, NEUS, WCTRI, WCANN, GMEX).

Many thanks
Aurore

**Comment by mstuart1** [comment]
Hi Aurore,

Thank you for looking at this.  
For topic 1 in your issue, the spptaxonomy.csv file contains a "taxon" column, which is values as they are found in the surveys.  The "name" column is the value they are converted to upon cleaning.  The spptaxonomy file is like a Rosetta Stone between how the data is reported to us and how we want to report the data (all caps vs. Genus spp in this case).  We cannot eliminate those all caps values.

For topic 2, I combined all spp found in all surveys and did an "anti-join" with the spptaxonomy.csv file to check which spp were in the survey spp list that were not in the taxon column of the spptaxonomy file.   There were 41 spp which I am guessing are trimmed out when we cut out spp that are not present in at least 3/4 of the surveys for a region. All but 7 of those 41 were found in fishbase/sealife base and added to the spptaxonomy.csv
